# Generated by Django 5.2.6 on 2025-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('equipment', 'Equipment')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('product_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
