# Generated by Django 5.2.6 on 2025-09-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(help_text='Sizes separated by commas', max_length=200, null=True),
        ),
    ]
