# Generated by Django 5.2.6 on 2025-10-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_size_product_available_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('equipment', 'Equipment')], default='equipment', max_length=20),
        ),
    ]
